rails/blog  (copy)/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

 devise_for :members
resources :posts

root :to => 'home#index'

end

rails/blog  (copy)/app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, :presence => true    
  validates :email, :presence => true
   has_attached_file :pic, :styles => 
           { :medium => "300x300>", :thumb => "100x100>" }
   has_attached_file :attach
               
end

rails/blog  (copy)/app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
 validates :description, presence: true
end

rails/blog  (copy)/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

rails/blog  (copy)/app/controllers/items_controller.rb
class ItemsController < ApplicationController
def index
end
def new
end
def show
end
def create
end
end

rails/blog  (copy)/app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_action :set_post, only: [:show, :edit, :update, :destroy]

def index
@posts = Post.all
end
def show
end
def new
@post = Post.new
end

def edit
  end

  
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'item was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @post.update(product_params)
        format.html { redirect_to @post, notice: 'item was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

 
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    
    def set_post
      @post = Post.find(params[:id])
    end

   
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

rails/blog  (copy)/app/controllers/registration_controller.rb
class RegistrationController < ApplicationController

def new

@member= Member.new
@contact = Contact.new
end

def create

@member = Member.new
@member.username = params[:member][:username]
@member.dob = params[:member][:DOB]
@member.gender = params[:member][:gender]
@member.email = params[:member][:email]
@member.password = params[:member][:password]
@member.password_confirmation =params[:member][:password_confirmation]

end
end

rails/blog  (copy)/app/helpers/home_helper.rb
module HomeHelper
end

rails/blog  (copy)/app/helpers/items_helper.rb
module ItemsHelper
end

rails/blog  (copy)/app/helpers/posts_helper.rb
module PostsHelper
end

rails/blog  (copy)/app/helpers/registration_helper.rb
module RegistrationHelper
end

rails/blog  (copy)/app/views/home/index.html.erb
<% if member_signed_in? %>

<h3>you have succesfully signed in</h3> </br>

<%= link_to "List Of Items" ,posts_path %> <br />
<br />
<%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>

<% else %>

<h1> Hiii Welcome</h1>
<%= link_to "Sign In", new_member_session_path, :method => :get %>
<%= link_to "Sign up", new_member_registration_path, :method => :get %>

<% end %>

rails/blog  (copy)/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/blog  (copy)/app/views/posts/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

rails/blog  (copy)/app/views/posts/index.html.erb
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
	
   
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
	<td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

rails/blog  (copy)/app/views/posts/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

rails/blog  (copy)/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>